//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from L1.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public partial class L1Parser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, NUMBER=31, 
		STRING=32, BOOLEAN=33, COMPARE=34, ARITH=35, MULT=36, OR=37, IDENT=38, 
		WHITESPACE=39;
	public const int
		RULE_program = 0, RULE_function = 1, RULE_type = 2, RULE_var_list = 3, 
		RULE_function_body = 4, RULE_fact_params = 5, RULE_op_definition = 6, 
		RULE_op_assign = 7, RULE_op_func_call = 8, RULE_op_if = 9, RULE_op_while_pre = 10, 
		RULE_op_while_post = 11, RULE_op_assert = 12, RULE_stmt = 13, RULE_expr = 14, 
		RULE_and_expr = 15, RULE_comp = 16, RULE_arith_expr = 17, RULE_term = 18, 
		RULE_factor = 19, RULE_power = 20, RULE_atom_expr = 21;
	public static readonly string[] ruleNames = {
		"program", "function", "type", "var_list", "function_body", "fact_params", 
		"op_definition", "op_assign", "op_func_call", "op_if", "op_while_pre", 
		"op_while_post", "op_assert", "stmt", "expr", "and_expr", "comp", "arith_expr", 
		"term", "factor", "power", "atom_expr"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'define'", "'('", "')'", "'end'", "'void'", "'int'", "'char'", 
		"'bool'", "'string'", "'int array'", "'char array'", "'bool array'", "','", 
		"'return'", "'\n'", "':='", "'if'", "'then'", "'elseif'", "'else'", "'while'", 
		"'do'", "'assert'", "'and'", "'-'", "'**'", "'['", "']'", "'new'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, "NUMBER", "STRING", "BOOLEAN", 
		"COMPARE", "ARITH", "MULT", "OR", "IDENT", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "L1.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static L1Parser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public L1Parser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public L1Parser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionContext[] function() {
			return GetRuleContexts<FunctionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionContext function(int i) {
			return GetRuleContext<FunctionContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 47;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 44; function();
				State = 45; Match(T__0);
				}
				}
				State = 49;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__1 );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(L1Parser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_listContext var_list() {
			return GetRuleContext<Var_listContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Function_bodyContext function_body() {
			return GetRuleContext<Function_bodyContext>(0);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterFunction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitFunction(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(Context, State);
		EnterRule(_localctx, 2, RULE_function);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 51; Match(T__1);
			State = 52; type();
			State = 53; Match(IDENT);
			State = 54; Match(T__2);
			State = 55; var_list();
			State = 56; Match(T__3);
			State = 57; function_body();
			State = 58; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitType(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 4, RULE_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__11) | (1L << T__12))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext[] type() {
			return GetRuleContexts<TypeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type(int i) {
			return GetRuleContext<TypeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENT() { return GetTokens(L1Parser.IDENT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT(int i) {
			return GetToken(L1Parser.IDENT, i);
		}
		public Var_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterVar_list(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitVar_list(this);
		}
	}

	[RuleVersion(0)]
	public Var_listContext var_list() {
		Var_listContext _localctx = new Var_listContext(Context, State);
		EnterRule(_localctx, 6, RULE_var_list);
		int _la;
		try {
			State = 74;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				EnterOuterAlt(_localctx, 1);
				{
				}
				break;
			case T__5:
			case T__6:
			case T__7:
			case T__8:
			case T__9:
			case T__10:
			case T__11:
			case T__12:
				EnterOuterAlt(_localctx, 2);
				{
				State = 63; type();
				State = 64; Match(IDENT);
				State = 71;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__13) {
					{
					{
					State = 65; Match(T__13);
					State = 66; type();
					State = 67; Match(IDENT);
					}
					}
					State = 73;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_bodyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public Function_bodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_body; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterFunction_body(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitFunction_body(this);
		}
	}

	[RuleVersion(0)]
	public Function_bodyContext function_body() {
		Function_bodyContext _localctx = new Function_bodyContext(Context, State);
		EnterRule(_localctx, 8, RULE_function_body);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__11) | (1L << T__12) | (1L << T__17) | (1L << T__21) | (1L << T__22) | (1L << T__23) | (1L << IDENT))) != 0)) {
				{
				{
				State = 76; stmt();
				State = 77; Match(T__0);
				}
				}
				State = 83;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 84; Match(T__14);
			State = 87;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__25:
			case T__29:
			case NUMBER:
			case STRING:
			case BOOLEAN:
			case IDENT:
				{
				State = 85; expr();
				}
				break;
			case T__0:
				{
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 89; Match(T__0);
			State = 90; Match(T__15);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Fact_paramsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public Fact_paramsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fact_params; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterFact_params(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitFact_params(this);
		}
	}

	[RuleVersion(0)]
	public Fact_paramsContext fact_params() {
		Fact_paramsContext _localctx = new Fact_paramsContext(Context, State);
		EnterRule(_localctx, 10, RULE_fact_params);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 102;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__25:
			case T__29:
			case NUMBER:
			case STRING:
			case BOOLEAN:
			case IDENT:
				{
				State = 97;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 92; expr();
						State = 93; Match(T__13);
						}
						} 
					}
					State = 99;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
				}
				State = 100; expr();
				}
				break;
			case T__3:
				{
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Op_definitionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(L1Parser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Op_definitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op_definition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterOp_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitOp_definition(this);
		}
	}

	[RuleVersion(0)]
	public Op_definitionContext op_definition() {
		Op_definitionContext _localctx = new Op_definitionContext(Context, State);
		EnterRule(_localctx, 12, RULE_op_definition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104; type();
			State = 105; Match(IDENT);
			State = 106; Match(T__16);
			State = 107; expr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Op_assignContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(L1Parser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Op_assignContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op_assign; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterOp_assign(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitOp_assign(this);
		}
	}

	[RuleVersion(0)]
	public Op_assignContext op_assign() {
		Op_assignContext _localctx = new Op_assignContext(Context, State);
		EnterRule(_localctx, 14, RULE_op_assign);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 109; Match(IDENT);
			State = 110; Match(T__16);
			State = 111; expr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Op_func_callContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(L1Parser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Fact_paramsContext fact_params() {
			return GetRuleContext<Fact_paramsContext>(0);
		}
		public Op_func_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op_func_call; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterOp_func_call(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitOp_func_call(this);
		}
	}

	[RuleVersion(0)]
	public Op_func_callContext op_func_call() {
		Op_func_callContext _localctx = new Op_func_callContext(Context, State);
		EnterRule(_localctx, 16, RULE_op_func_call);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113; Match(IDENT);
			State = 114; Match(T__2);
			State = 115; fact_params();
			State = 116; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Op_ifContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public Op_ifContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op_if; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterOp_if(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitOp_if(this);
		}
	}

	[RuleVersion(0)]
	public Op_ifContext op_if() {
		Op_ifContext _localctx = new Op_ifContext(Context, State);
		EnterRule(_localctx, 18, RULE_op_if);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118; Match(T__17);
			State = 119; expr();
			State = 120; Match(T__18);
			State = 124;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__11) | (1L << T__12) | (1L << T__17) | (1L << T__21) | (1L << T__22) | (1L << T__23) | (1L << IDENT))) != 0)) {
				{
				{
				State = 121; stmt();
				}
				}
				State = 126;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 138;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__19) {
				{
				{
				State = 127; Match(T__19);
				State = 128; expr();
				State = 129; Match(T__18);
				State = 133;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__11) | (1L << T__12) | (1L << T__17) | (1L << T__21) | (1L << T__22) | (1L << T__23) | (1L << IDENT))) != 0)) {
					{
					{
					State = 130; stmt();
					}
					}
					State = 135;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				}
				State = 140;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 148;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__20) {
				{
				State = 141; Match(T__20);
				State = 145;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__11) | (1L << T__12) | (1L << T__17) | (1L << T__21) | (1L << T__22) | (1L << T__23) | (1L << IDENT))) != 0)) {
					{
					{
					State = 142; stmt();
					}
					}
					State = 147;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 150; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Op_while_preContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public Op_while_preContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op_while_pre; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterOp_while_pre(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitOp_while_pre(this);
		}
	}

	[RuleVersion(0)]
	public Op_while_preContext op_while_pre() {
		Op_while_preContext _localctx = new Op_while_preContext(Context, State);
		EnterRule(_localctx, 20, RULE_op_while_pre);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 152; Match(T__21);
			State = 153; expr();
			State = 154; Match(T__22);
			State = 158;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__11) | (1L << T__12) | (1L << T__17) | (1L << T__21) | (1L << T__22) | (1L << T__23) | (1L << IDENT))) != 0)) {
				{
				{
				State = 155; stmt();
				}
				}
				State = 160;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 161; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Op_while_postContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public Op_while_postContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op_while_post; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterOp_while_post(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitOp_while_post(this);
		}
	}

	[RuleVersion(0)]
	public Op_while_postContext op_while_post() {
		Op_while_postContext _localctx = new Op_while_postContext(Context, State);
		EnterRule(_localctx, 22, RULE_op_while_post);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 163; Match(T__22);
			State = 169;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 164; stmt();
					State = 165; Match(T__0);
					}
					} 
				}
				State = 171;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			}
			State = 172; Match(T__21);
			State = 173; expr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Op_assertContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Op_assertContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op_assert; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterOp_assert(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitOp_assert(this);
		}
	}

	[RuleVersion(0)]
	public Op_assertContext op_assert() {
		Op_assertContext _localctx = new Op_assertContext(Context, State);
		EnterRule(_localctx, 24, RULE_op_assert);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 175; Match(T__23);
			State = 176; expr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Op_definitionContext op_definition() {
			return GetRuleContext<Op_definitionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Op_assignContext op_assign() {
			return GetRuleContext<Op_assignContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Op_func_callContext op_func_call() {
			return GetRuleContext<Op_func_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Op_ifContext op_if() {
			return GetRuleContext<Op_ifContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Op_while_preContext op_while_pre() {
			return GetRuleContext<Op_while_preContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Op_while_postContext op_while_post() {
			return GetRuleContext<Op_while_postContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Op_assertContext op_assert() {
			return GetRuleContext<Op_assertContext>(0);
		}
		public StmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterStmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitStmt(this);
		}
	}

	[RuleVersion(0)]
	public StmtContext stmt() {
		StmtContext _localctx = new StmtContext(Context, State);
		EnterRule(_localctx, 26, RULE_stmt);
		try {
			State = 185;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 178; op_definition();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 179; op_assign();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 180; op_func_call();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 181; op_if();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 182; op_while_pre();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 183; op_while_post();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 184; op_assert();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public And_exprContext[] and_expr() {
			return GetRuleContexts<And_exprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public And_exprContext and_expr(int i) {
			return GetRuleContext<And_exprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] OR() { return GetTokens(L1Parser.OR); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR(int i) {
			return GetToken(L1Parser.OR, i);
		}
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		ExprContext _localctx = new ExprContext(Context, State);
		EnterRule(_localctx, 28, RULE_expr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 187; and_expr();
			State = 192;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==OR) {
				{
				{
				State = 188; Match(OR);
				State = 189; and_expr();
				}
				}
				State = 194;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class And_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CompContext[] comp() {
			return GetRuleContexts<CompContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CompContext comp(int i) {
			return GetRuleContext<CompContext>(i);
		}
		public And_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_and_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterAnd_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitAnd_expr(this);
		}
	}

	[RuleVersion(0)]
	public And_exprContext and_expr() {
		And_exprContext _localctx = new And_exprContext(Context, State);
		EnterRule(_localctx, 30, RULE_and_expr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 195; comp();
			State = 200;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__24) {
				{
				{
				State = 196; Match(T__24);
				State = 197; comp();
				}
				}
				State = 202;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CompContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arith_exprContext[] arith_expr() {
			return GetRuleContexts<Arith_exprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arith_exprContext arith_expr(int i) {
			return GetRuleContext<Arith_exprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMPARE() { return GetTokens(L1Parser.COMPARE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMPARE(int i) {
			return GetToken(L1Parser.COMPARE, i);
		}
		public CompContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterComp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitComp(this);
		}
	}

	[RuleVersion(0)]
	public CompContext comp() {
		CompContext _localctx = new CompContext(Context, State);
		EnterRule(_localctx, 32, RULE_comp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 203; arith_expr();
			State = 208;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMPARE) {
				{
				{
				State = 204; Match(COMPARE);
				State = 205; arith_expr();
				}
				}
				State = 210;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arith_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TermContext[] term() {
			return GetRuleContexts<TermContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term(int i) {
			return GetRuleContext<TermContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ARITH() { return GetTokens(L1Parser.ARITH); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARITH(int i) {
			return GetToken(L1Parser.ARITH, i);
		}
		public Arith_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arith_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterArith_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitArith_expr(this);
		}
	}

	[RuleVersion(0)]
	public Arith_exprContext arith_expr() {
		Arith_exprContext _localctx = new Arith_exprContext(Context, State);
		EnterRule(_localctx, 34, RULE_arith_expr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 211; term();
			State = 216;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==ARITH) {
				{
				{
				State = 212; Match(ARITH);
				State = 213; term();
				}
				}
				State = 218;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TermContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext[] factor() {
			return GetRuleContexts<FactorContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext factor(int i) {
			return GetRuleContext<FactorContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MULT() { return GetTokens(L1Parser.MULT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT(int i) {
			return GetToken(L1Parser.MULT, i);
		}
		public TermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_term; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterTerm(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitTerm(this);
		}
	}

	[RuleVersion(0)]
	public TermContext term() {
		TermContext _localctx = new TermContext(Context, State);
		EnterRule(_localctx, 36, RULE_term);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 219; factor();
			State = 224;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==MULT) {
				{
				{
				State = 220; Match(MULT);
				State = 221; factor();
				}
				}
				State = 226;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FactorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PowerContext power() {
			return GetRuleContext<PowerContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext factor() {
			return GetRuleContext<FactorContext>(0);
		}
		public FactorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_factor; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterFactor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitFactor(this);
		}
	}

	[RuleVersion(0)]
	public FactorContext factor() {
		FactorContext _localctx = new FactorContext(Context, State);
		EnterRule(_localctx, 38, RULE_factor);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 230;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__29:
			case NUMBER:
			case STRING:
			case BOOLEAN:
			case IDENT:
				{
				State = 227; power();
				}
				break;
			case T__25:
				{
				State = 228; Match(T__25);
				State = 229; factor();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PowerContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Atom_exprContext atom_expr() {
			return GetRuleContext<Atom_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext factor() {
			return GetRuleContext<FactorContext>(0);
		}
		public PowerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_power; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterPower(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitPower(this);
		}
	}

	[RuleVersion(0)]
	public PowerContext power() {
		PowerContext _localctx = new PowerContext(Context, State);
		EnterRule(_localctx, 40, RULE_power);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 232; atom_expr();
			State = 235;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__26) {
				{
				State = 233; Match(T__26);
				State = 234; factor();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Atom_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(L1Parser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(L1Parser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(L1Parser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN() { return GetToken(L1Parser.BOOLEAN, 0); }
		public Atom_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.EnterAtom_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IL1Listener typedListener = listener as IL1Listener;
			if (typedListener != null) typedListener.ExitAtom_expr(this);
		}
	}

	[RuleVersion(0)]
	public Atom_exprContext atom_expr() {
		Atom_exprContext _localctx = new Atom_exprContext(Context, State);
		EnterRule(_localctx, 42, RULE_atom_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 257;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
			case 1:
				{
				State = 237; Match(IDENT);
				State = 238; Match(T__27);
				State = 239; expr();
				State = 240; Match(T__28);
				}
				break;
			case 2:
				{
				State = 242; Match(IDENT);
				State = 243; Match(T__27);
				State = 244; expr();
				State = 245; Match(T__28);
				}
				break;
			case 3:
				{
				State = 247; Match(T__29);
				State = 248; type();
				State = 249; Match(T__27);
				State = 250; expr();
				State = 251; Match(T__28);
				}
				break;
			case 4:
				{
				State = 253; Match(IDENT);
				}
				break;
			case 5:
				{
				State = 254; Match(NUMBER);
				}
				break;
			case 6:
				{
				State = 255; Match(STRING);
				}
				break;
			case 7:
				{
				State = 256; Match(BOOLEAN);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', ')', '\x106', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x6', '\x2', '\x32', '\n', '\x2', '\r', '\x2', '\xE', 
		'\x2', '\x33', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', 'H', 
		'\n', '\x5', '\f', '\x5', '\xE', '\x5', 'K', '\v', '\x5', '\x5', '\x5', 
		'M', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 
		'R', '\n', '\x6', '\f', '\x6', '\xE', '\x6', 'U', '\v', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', 'Z', '\n', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\a', '\a', '\x62', '\n', '\a', '\f', '\a', '\xE', '\a', '\x65', '\v', 
		'\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', 'i', '\n', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\a', '\v', '}', '\n', '\v', '\f', '\v', '\xE', '\v', '\x80', '\v', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\a', '\v', 
		'\x86', '\n', '\v', '\f', '\v', '\xE', '\v', '\x89', '\v', '\v', '\a', 
		'\v', '\x8B', '\n', '\v', '\f', '\v', '\xE', '\v', '\x8E', '\v', '\v', 
		'\x3', '\v', '\x3', '\v', '\a', '\v', '\x92', '\n', '\v', '\f', '\v', 
		'\xE', '\v', '\x95', '\v', '\v', '\x5', '\v', '\x97', '\n', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\a', '\f', '\x9F', '\n', '\f', '\f', '\f', '\xE', '\f', '\xA2', '\v', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\a', '\r', '\xAA', '\n', '\r', '\f', '\r', '\xE', '\r', 
		'\xAD', '\v', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', '\xF', 
		'\xBC', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\a', 
		'\x10', '\xC1', '\n', '\x10', '\f', '\x10', '\xE', '\x10', '\xC4', '\v', 
		'\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\a', '\x11', '\xC9', 
		'\n', '\x11', '\f', '\x11', '\xE', '\x11', '\xCC', '\v', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', '\xD1', '\n', '\x12', 
		'\f', '\x12', '\xE', '\x12', '\xD4', '\v', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\a', '\x13', '\xD9', '\n', '\x13', '\f', '\x13', 
		'\xE', '\x13', '\xDC', '\v', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\a', '\x14', '\xE1', '\n', '\x14', '\f', '\x14', '\xE', '\x14', 
		'\xE4', '\v', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x5', 
		'\x15', '\xE9', '\n', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x5', '\x16', '\xEE', '\n', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x5', '\x17', '\x104', '\n', '\x17', 
		'\x3', '\x17', '\x2', '\x2', '\x18', '\x2', '\x4', '\x6', '\b', '\n', 
		'\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', 
		' ', '\"', '$', '&', '(', '*', ',', '\x2', '\x3', '\x3', '\x2', '\b', 
		'\xF', '\x2', '\x110', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x4', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\x6', '>', '\x3', '\x2', '\x2', '\x2', 
		'\b', 'L', '\x3', '\x2', '\x2', '\x2', '\n', 'S', '\x3', '\x2', '\x2', 
		'\x2', '\f', 'h', '\x3', '\x2', '\x2', '\x2', '\xE', 'j', '\x3', '\x2', 
		'\x2', '\x2', '\x10', 'o', '\x3', '\x2', '\x2', '\x2', '\x12', 's', '\x3', 
		'\x2', '\x2', '\x2', '\x14', 'x', '\x3', '\x2', '\x2', '\x2', '\x16', 
		'\x9A', '\x3', '\x2', '\x2', '\x2', '\x18', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\x1A', '\xB1', '\x3', '\x2', '\x2', '\x2', '\x1C', '\xBB', '\x3', 
		'\x2', '\x2', '\x2', '\x1E', '\xBD', '\x3', '\x2', '\x2', '\x2', ' ', 
		'\xC5', '\x3', '\x2', '\x2', '\x2', '\"', '\xCD', '\x3', '\x2', '\x2', 
		'\x2', '$', '\xD5', '\x3', '\x2', '\x2', '\x2', '&', '\xDD', '\x3', '\x2', 
		'\x2', '\x2', '(', '\xE8', '\x3', '\x2', '\x2', '\x2', '*', '\xEA', '\x3', 
		'\x2', '\x2', '\x2', ',', '\x103', '\x3', '\x2', '\x2', '\x2', '.', '/', 
		'\x5', '\x4', '\x3', '\x2', '/', '\x30', '\a', '\x3', '\x2', '\x2', '\x30', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\x31', '.', '\x3', '\x2', '\x2', 
		'\x2', '\x32', '\x33', '\x3', '\x2', '\x2', '\x2', '\x33', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x34', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', '\x4', '\x2', 
		'\x2', '\x36', '\x37', '\x5', '\x6', '\x4', '\x2', '\x37', '\x38', '\a', 
		'(', '\x2', '\x2', '\x38', '\x39', '\a', '\x5', '\x2', '\x2', '\x39', 
		':', '\x5', '\b', '\x5', '\x2', ':', ';', '\a', '\x6', '\x2', '\x2', ';', 
		'<', '\x5', '\n', '\x6', '\x2', '<', '=', '\a', '\a', '\x2', '\x2', '=', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '>', '?', '\t', '\x2', '\x2', '\x2', 
		'?', '\a', '\x3', '\x2', '\x2', '\x2', '@', 'M', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\x42', '\x5', '\x6', '\x4', '\x2', '\x42', 'I', '\a', 
		'(', '\x2', '\x2', '\x43', '\x44', '\a', '\x10', '\x2', '\x2', '\x44', 
		'\x45', '\x5', '\x6', '\x4', '\x2', '\x45', '\x46', '\a', '(', '\x2', 
		'\x2', '\x46', 'H', '\x3', '\x2', '\x2', '\x2', 'G', '\x43', '\x3', '\x2', 
		'\x2', '\x2', 'H', 'K', '\x3', '\x2', '\x2', '\x2', 'I', 'G', '\x3', '\x2', 
		'\x2', '\x2', 'I', 'J', '\x3', '\x2', '\x2', '\x2', 'J', 'M', '\x3', '\x2', 
		'\x2', '\x2', 'K', 'I', '\x3', '\x2', '\x2', '\x2', 'L', '@', '\x3', '\x2', 
		'\x2', '\x2', 'L', '\x41', '\x3', '\x2', '\x2', '\x2', 'M', '\t', '\x3', 
		'\x2', '\x2', '\x2', 'N', 'O', '\x5', '\x1C', '\xF', '\x2', 'O', 'P', 
		'\a', '\x3', '\x2', '\x2', 'P', 'R', '\x3', '\x2', '\x2', '\x2', 'Q', 
		'N', '\x3', '\x2', '\x2', '\x2', 'R', 'U', '\x3', '\x2', '\x2', '\x2', 
		'S', 'Q', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\x3', '\x2', '\x2', '\x2', 
		'T', 'V', '\x3', '\x2', '\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 
		'V', 'Y', '\a', '\x11', '\x2', '\x2', 'W', 'Z', '\x5', '\x1E', '\x10', 
		'\x2', 'X', 'Z', '\x3', '\x2', '\x2', '\x2', 'Y', 'W', '\x3', '\x2', '\x2', 
		'\x2', 'Y', 'X', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\a', '\x3', '\x2', '\x2', '\\', ']', '\a', '\x12', 
		'\x2', '\x2', ']', '\v', '\x3', '\x2', '\x2', '\x2', '^', '_', '\x5', 
		'\x1E', '\x10', '\x2', '_', '`', '\a', '\x10', '\x2', '\x2', '`', '\x62', 
		'\x3', '\x2', '\x2', '\x2', '\x61', '^', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x65', '\x3', '\x2', '\x2', '\x2', '\x63', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\x3', '\x2', '\x2', '\x2', '\x64', '\x66', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'i', '\x5', '\x1E', '\x10', '\x2', 'g', 'i', '\x3', '\x2', '\x2', '\x2', 
		'h', '\x63', '\x3', '\x2', '\x2', '\x2', 'h', 'g', '\x3', '\x2', '\x2', 
		'\x2', 'i', '\r', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\x5', '\x6', 
		'\x4', '\x2', 'k', 'l', '\a', '(', '\x2', '\x2', 'l', 'm', '\a', '\x13', 
		'\x2', '\x2', 'm', 'n', '\x5', '\x1E', '\x10', '\x2', 'n', '\xF', '\x3', 
		'\x2', '\x2', '\x2', 'o', 'p', '\a', '(', '\x2', '\x2', 'p', 'q', '\a', 
		'\x13', '\x2', '\x2', 'q', 'r', '\x5', '\x1E', '\x10', '\x2', 'r', '\x11', 
		'\x3', '\x2', '\x2', '\x2', 's', 't', '\a', '(', '\x2', '\x2', 't', 'u', 
		'\a', '\x5', '\x2', '\x2', 'u', 'v', '\x5', '\f', '\a', '\x2', 'v', 'w', 
		'\a', '\x6', '\x2', '\x2', 'w', '\x13', '\x3', '\x2', '\x2', '\x2', 'x', 
		'y', '\a', '\x14', '\x2', '\x2', 'y', 'z', '\x5', '\x1E', '\x10', '\x2', 
		'z', '~', '\a', '\x15', '\x2', '\x2', '{', '}', '\x5', '\x1C', '\xF', 
		'\x2', '|', '{', '\x3', '\x2', '\x2', '\x2', '}', '\x80', '\x3', '\x2', 
		'\x2', '\x2', '~', '|', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\x3', 
		'\x2', '\x2', '\x2', '\x7F', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x80', 
		'~', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\a', '\x16', '\x2', 
		'\x2', '\x82', '\x83', '\x5', '\x1E', '\x10', '\x2', '\x83', '\x87', '\a', 
		'\x15', '\x2', '\x2', '\x84', '\x86', '\x5', '\x1C', '\xF', '\x2', '\x85', 
		'\x84', '\x3', '\x2', '\x2', '\x2', '\x86', '\x89', '\x3', '\x2', '\x2', 
		'\x2', '\x87', '\x85', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\x3', 
		'\x2', '\x2', '\x2', '\x88', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x89', 
		'\x87', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8A', '\x3', 
		'\x2', '\x2', '\x2', '\x8C', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x93', '\a', '\x17', '\x2', '\x2', '\x90', '\x92', '\x5', 
		'\x1C', '\xF', '\x2', '\x91', '\x90', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x93', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x94', '\x3', '\x2', '\x2', '\x2', '\x94', '\x97', '\x3', 
		'\x2', '\x2', '\x2', '\x95', '\x93', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\x3', '\x2', '\x2', 
		'\x2', '\x97', '\x98', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\a', 
		'\a', '\x2', '\x2', '\x99', '\x15', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x9B', '\a', '\x18', '\x2', '\x2', '\x9B', '\x9C', '\x5', '\x1E', '\x10', 
		'\x2', '\x9C', '\xA0', '\a', '\x19', '\x2', '\x2', '\x9D', '\x9F', '\x5', 
		'\x1C', '\xF', '\x2', '\x9E', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x9E', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA3', '\x3', 
		'\x2', '\x2', '\x2', '\xA2', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA3', 
		'\xA4', '\a', '\a', '\x2', '\x2', '\xA4', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\xA5', '\xAB', '\a', '\x19', '\x2', '\x2', '\xA6', '\xA7', '\x5', 
		'\x1C', '\xF', '\x2', '\xA7', '\xA8', '\a', '\x3', '\x2', '\x2', '\xA8', 
		'\xAA', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xA6', '\x3', '\x2', '\x2', 
		'\x2', '\xAA', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xA9', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xAE', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAB', '\x3', '\x2', '\x2', 
		'\x2', '\xAE', '\xAF', '\a', '\x18', '\x2', '\x2', '\xAF', '\xB0', '\x5', 
		'\x1E', '\x10', '\x2', '\xB0', '\x19', '\x3', '\x2', '\x2', '\x2', '\xB1', 
		'\xB2', '\a', '\x1A', '\x2', '\x2', '\xB2', '\xB3', '\x5', '\x1E', '\x10', 
		'\x2', '\xB3', '\x1B', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xBC', '\x5', 
		'\xE', '\b', '\x2', '\xB5', '\xBC', '\x5', '\x10', '\t', '\x2', '\xB6', 
		'\xBC', '\x5', '\x12', '\n', '\x2', '\xB7', '\xBC', '\x5', '\x14', '\v', 
		'\x2', '\xB8', '\xBC', '\x5', '\x16', '\f', '\x2', '\xB9', '\xBC', '\x5', 
		'\x18', '\r', '\x2', '\xBA', '\xBC', '\x5', '\x1A', '\xE', '\x2', '\xBB', 
		'\xB4', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xB5', '\x3', '\x2', '\x2', 
		'\x2', '\xBB', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\xBB', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xBB', 
		'\xB9', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBA', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', '\x1D', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xC2', '\x5', 
		' ', '\x11', '\x2', '\xBE', '\xBF', '\a', '\'', '\x2', '\x2', '\xBF', 
		'\xC1', '\x5', ' ', '\x11', '\x2', '\xC0', '\xBE', '\x3', '\x2', '\x2', 
		'\x2', '\xC1', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC0', '\x3', 
		'\x2', '\x2', '\x2', '\xC2', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC3', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC2', '\x3', '\x2', '\x2', 
		'\x2', '\xC5', '\xCA', '\x5', '\"', '\x12', '\x2', '\xC6', '\xC7', '\a', 
		'\x1B', '\x2', '\x2', '\xC7', '\xC9', '\x5', '\"', '\x12', '\x2', '\xC8', 
		'\xC6', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCC', '\x3', '\x2', '\x2', 
		'\x2', '\xCA', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '!', '\x3', '\x2', '\x2', '\x2', '\xCC', 
		'\xCA', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xD2', '\x5', '$', '\x13', 
		'\x2', '\xCE', '\xCF', '\a', '$', '\x2', '\x2', '\xCF', '\xD1', '\x5', 
		'$', '\x13', '\x2', '\xD0', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xD1', 
		'\xD4', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD0', '\x3', '\x2', '\x2', 
		'\x2', '\xD2', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD3', '#', '\x3', 
		'\x2', '\x2', '\x2', '\xD4', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD5', 
		'\xDA', '\x5', '&', '\x14', '\x2', '\xD6', '\xD7', '\a', '%', '\x2', '\x2', 
		'\xD7', '\xD9', '\x5', '&', '\x14', '\x2', '\xD8', '\xD6', '\x3', '\x2', 
		'\x2', '\x2', '\xD9', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xD8', 
		'\x3', '\x2', '\x2', '\x2', '\xDA', '\xDB', '\x3', '\x2', '\x2', '\x2', 
		'\xDB', '%', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDA', '\x3', '\x2', 
		'\x2', '\x2', '\xDD', '\xE2', '\x5', '(', '\x15', '\x2', '\xDE', '\xDF', 
		'\a', '&', '\x2', '\x2', '\xDF', '\xE1', '\x5', '(', '\x15', '\x2', '\xE0', 
		'\xDE', '\x3', '\x2', '\x2', '\x2', '\xE1', '\xE4', '\x3', '\x2', '\x2', 
		'\x2', '\xE2', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xE2', '\xE3', '\x3', 
		'\x2', '\x2', '\x2', '\xE3', '\'', '\x3', '\x2', '\x2', '\x2', '\xE4', 
		'\xE2', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE9', '\x5', '*', '\x16', 
		'\x2', '\xE6', '\xE7', '\a', '\x1C', '\x2', '\x2', '\xE7', '\xE9', '\x5', 
		'(', '\x15', '\x2', '\xE8', '\xE5', '\x3', '\x2', '\x2', '\x2', '\xE8', 
		'\xE6', '\x3', '\x2', '\x2', '\x2', '\xE9', ')', '\x3', '\x2', '\x2', 
		'\x2', '\xEA', '\xED', '\x5', ',', '\x17', '\x2', '\xEB', '\xEC', '\a', 
		'\x1D', '\x2', '\x2', '\xEC', '\xEE', '\x5', '(', '\x15', '\x2', '\xED', 
		'\xEB', '\x3', '\x2', '\x2', '\x2', '\xED', '\xEE', '\x3', '\x2', '\x2', 
		'\x2', '\xEE', '+', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xF0', '\a', 
		'(', '\x2', '\x2', '\xF0', '\xF1', '\a', '\x1E', '\x2', '\x2', '\xF1', 
		'\xF2', '\x5', '\x1E', '\x10', '\x2', '\xF2', '\xF3', '\a', '\x1F', '\x2', 
		'\x2', '\xF3', '\x104', '\x3', '\x2', '\x2', '\x2', '\xF4', '\xF5', '\a', 
		'(', '\x2', '\x2', '\xF5', '\xF6', '\a', '\x1E', '\x2', '\x2', '\xF6', 
		'\xF7', '\x5', '\x1E', '\x10', '\x2', '\xF7', '\xF8', '\a', '\x1F', '\x2', 
		'\x2', '\xF8', '\x104', '\x3', '\x2', '\x2', '\x2', '\xF9', '\xFA', '\a', 
		' ', '\x2', '\x2', '\xFA', '\xFB', '\x5', '\x6', '\x4', '\x2', '\xFB', 
		'\xFC', '\a', '\x1E', '\x2', '\x2', '\xFC', '\xFD', '\x5', '\x1E', '\x10', 
		'\x2', '\xFD', '\xFE', '\a', '\x1F', '\x2', '\x2', '\xFE', '\x104', '\x3', 
		'\x2', '\x2', '\x2', '\xFF', '\x104', '\a', '(', '\x2', '\x2', '\x100', 
		'\x104', '\a', '!', '\x2', '\x2', '\x101', '\x104', '\a', '\"', '\x2', 
		'\x2', '\x102', '\x104', '\a', '#', '\x2', '\x2', '\x103', '\xEF', '\x3', 
		'\x2', '\x2', '\x2', '\x103', '\xF4', '\x3', '\x2', '\x2', '\x2', '\x103', 
		'\xF9', '\x3', '\x2', '\x2', '\x2', '\x103', '\xFF', '\x3', '\x2', '\x2', 
		'\x2', '\x103', '\x100', '\x3', '\x2', '\x2', '\x2', '\x103', '\x101', 
		'\x3', '\x2', '\x2', '\x2', '\x103', '\x102', '\x3', '\x2', '\x2', '\x2', 
		'\x104', '-', '\x3', '\x2', '\x2', '\x2', '\x19', '\x33', 'I', 'L', 'S', 
		'Y', '\x63', 'h', '~', '\x87', '\x8C', '\x93', '\x96', '\xA0', '\xAB', 
		'\xBB', '\xC2', '\xCA', '\xD2', '\xDA', '\xE2', '\xE8', '\xED', '\x103',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
